Mp fix
altibiz/altibiz-web pull request #14
Opened 2023-10-26 10:18 UTC by MajaPol

Dodana fav ikonica, dodane klase iz theme.css i u theme.min.css.

2023-11-02 13:39 UTC, MajaPol commented
opet treba approveat

2023-11-09 18:10 UTC, brunoAltinet requested changes

2023-11-09 18:10 UTC, brunoAltinet commented on AltibizTheme/Views/Layout.liquid
> +    {% link type:"image/x-icon", rel:"shortcut icon", href:"media/altibiz-logo/altibiz-favicon.png" %}
tilda (~) je bolji pristup, ovako kada je relative path (dakle bez / ili tilde ili iceg drugog) se lako slomi dohvat

2023-12-13 10:36 UTC, brunoAltinet approved these changes

2023-12-13 10:36 UTC, merged